#!/usr/bin/env python3
"""Pool several non-overlapping-seed run batches of the same 9 cells into one
combined *analysis* tag.

Motivating case: ``qwen3.5-4b_seed1``, ``qwen3.5-4b_seed2``,
``qwen3.5-4b_seed3`` (task seeds #1, #2, #3 of each of the 9
synthetic/tcas/physics x C0/C1/I1 cells, each generated by
``make_configs.py --seed-index``) should become one pooled
``qwen3.5-4b_seed1-3`` batch with all three seeds, without re-running any of
them:

    python3 scripts/merge_runs.py --out-tag qwen3.5-4b_seed1-3 \\
        --from-tags qwen3.5-4b_seed1 qwen3.5-4b_seed2 qwen3.5-4b_seed3

For each of the 9 ``{synthetic,tcas,physics} x {C0,C1,I1}`` cells this reads
the merged run directories ``runs/agents/<from_tag>/<from_tag>_<cell>_<policy>/``
of every ``--from-tags`` entry and writes
``runs/agents/<out_tag>/<out_tag>_<cell>_<policy>/`` with:

* ``episodes.jsonl`` / ``events.jsonl`` / ``requests.jsonl`` /
  ``responses.jsonl`` concatenated, reordered so records are grouped by
  episode id (``d<degree>_t<task_seed>_r<repeat>``) and the groups appear
  degree-major then task-seed, exactly as ``driver.py::episode_plan`` would
  order a single run with the union task-seed list;
* ``manifest.json`` recording the source tags/run dirs and a config whose
  ``task_seeds`` is the union of the sources' task seeds, in ascending
  (reference seed-list) order;
* ``run_summary.json`` with ``llm_usage`` and per-status episode counts
  summed across sources.

An out-tag produced this way is a *pooled analysis view*, not a new task
seed: it exists only under ``runs/agents/<out_tag>/`` (merged records +
manifest, and later ``dc_table.*``). It never gets a
``configs/agents/<out_tag>/`` folder -- there is no separate config to
maintain, since the merged config is fully determined by (and stored
alongside) the merged run data in each cell's ``manifest.json``.
``scripts/dc_table.py`` reads the cell config from that ``manifest.json``
when present, falling back to ``configs/agents/<tag>/`` for an ordinary
(single-seed) tag.

The ``shards/`` subdirectory of each source run is never read or copied, and
no source file is modified. The merge refuses (raising ``MergeError``,
reported as a single non-zero-exit error covering every offending cell) if,
for any of the 9 cells:

* a source run directory is missing, or missing ``run_summary.json`` /
  ``episodes.jsonl``;
* a source run has any failed shard or any non-``"ok"`` episode status
  (unless ``--allow-failed`` is passed -- see below), or fewer episodes than
  its own config plans (``len(degrees) * len(task_seeds) * repeats``) -- i.e.
  it looks incomplete;
* the sources' configs differ in any field other than ``name``, ``notes``,
  ``output_root``, ``task_seeds``;
* the sources' ``task_seeds`` overlap.

With ``--allow-failed`` (default off), a source cell whose only problem is a
terminal episode failure status (e.g. ``policy_failed``, possibly alongside a
matching ``failed_shards`` entry for the same shard) is merged anyway: its
episode records are included as-is -- the downstream analysis
(``critical_degree.pooled_log_ratio`` / ``pooled_step_log_ratio``) already
filters to ``status == "ok"`` episodes, and ``summarize.py`` reports every
status it sees -- and every one of them is recorded, in merged (output)
order, in the merged cell's ``manifest.json`` and ``run_summary.json`` under
``failed_episodes``: ``[{episode_id, d, task_seed, status, error (first 200
chars), source_tag}, ...]``. ``run_summary.json["statuses"]`` is (as before)
recomputed from the merged ``episodes.jsonl``, so it already carries the real,
non-``"ok"`` counts. Missing files, missing episodes (fewer than planned),
config mismatches and overlapping seeds are refused either way --
``--allow-failed`` only relaxes the failed-shard / non-ok-status checks.

Validation runs for all 9 cells before anything is written, so a bad cell
never leaves a partial merge on disk.
"""

from __future__ import annotations

import argparse
from datetime import datetime, timezone
import json
from pathlib import Path
import re
import sys
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[1]

CELLS = ["synthetic", "tcas", "physics"]
POLICIES = ["C0", "C1", "I1"]
MERGED_FILES = ("episodes.jsonl", "events.jsonl", "requests.jsonl", "responses.jsonl")
CONFIG_INVARIANT_KEYS = ("name", "notes", "output_root", "task_seeds")
EPISODE_ID_RE = re.compile(r"^d(\d+)_t(\d+)_r(\d+)$")


class MergeError(RuntimeError):
    """Raised to refuse a merge; the message lists every offending cell."""


def utc_now() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="seconds")


def config_path(configs_root: Path, tag: str, cell: str, policy: str) -> Path:
    return configs_root / tag / f"{cell}_{policy}.json"


def run_dir(runs_root: Path, tag: str, cell: str, policy: str) -> Path:
    return runs_root / tag / f"{tag}_{cell}_{policy}"


def load_json(path: Path) -> Any:
    return json.loads(path.read_text(encoding="utf-8"))


def load_jsonl(path: Path) -> list[dict]:
    if not path.exists():
        return []
    records = []
    for line in path.read_text(encoding="utf-8").splitlines():
        if line.strip():
            records.append(json.loads(line))
    return records


def episode_key(record: dict) -> str:
    key = record.get("episode_id") or record.get("episode")
    if key is None:
        raise MergeError(f"record has neither 'episode_id' nor 'episode': {record!r}")
    return key


def parse_episode_key(key: str) -> tuple[int, int, int]:
    match = EPISODE_ID_RE.match(key)
    if not match:
        raise MergeError(f"episode id {key!r} does not match d<degree>_t<seed>_r<repeat>")
    degree, task_seed, repeat = match.groups()
    return int(degree), int(task_seed), int(repeat)


def check_source(
    tag: str, cell: str, policy: str, cfg: dict, rdir: Path, allow_failed: bool = False
) -> dict:
    """Validate one source cell is complete; return its run_summary.json.

    With ``allow_failed``, a cell whose only problem is a terminal episode
    failure status (e.g. ``policy_failed``) -- optionally alongside a
    matching ``failed_shards`` entry for the same shard -- is accepted: the
    episode record is still there (see the "missing episodes" check below,
    which stays unconditional), just marked failed instead of ``"ok"``.
    Missing files, missing episodes (fewer than the config plans), config
    mismatches and overlapping seeds are refused either way -- those are
    handled elsewhere (here, and in ``check_configs_compatible`` /
    ``check_seeds_disjoint``).
    """
    problems = []
    if not rdir.is_dir():
        raise MergeError(f"{tag}/{cell}_{policy}: run dir not found: {rdir}")
    summary_path = rdir / "run_summary.json"
    episodes_path = rdir / "episodes.jsonl"
    if not summary_path.exists():
        problems.append(f"missing {summary_path}")
    if not episodes_path.exists():
        problems.append(f"missing {episodes_path}")
    if problems:
        raise MergeError(f"{tag}/{cell}_{policy}: incomplete -- " + "; ".join(problems))

    summary = load_json(summary_path)
    if summary.get("failed_shards") and not allow_failed:
        raise MergeError(
            f"{tag}/{cell}_{policy}: incomplete -- run_summary.json has "
            f"failed_shards={summary['failed_shards']!r} (pass --allow-failed to merge "
            "anyway and record the failed episodes)"
        )
    statuses = summary.get("statuses") or {}
    non_ok = {status: count for status, count in statuses.items() if status != "ok" and count}
    if non_ok and not allow_failed:
        raise MergeError(
            f"{tag}/{cell}_{policy}: incomplete -- non-ok episode statuses {non_ok!r} "
            "(pass --allow-failed to merge anyway and record the failed episodes)"
        )
    episodes = load_jsonl(episodes_path)
    expected = len(cfg["degrees"]) * len(cfg["task_seeds"]) * cfg.get("repeats", 1)
    if len(episodes) < expected:
        raise MergeError(
            f"{tag}/{cell}_{policy}: incomplete -- {len(episodes)} episodes recorded, "
            f"expected {expected} from its config (degrees x task_seeds x repeats)"
        )
    return summary


def check_configs_compatible(cell: str, policy: str, configs: dict[str, dict]) -> None:
    tags = list(configs)
    base_tag = tags[0]
    base = {k: v for k, v in configs[base_tag].items() if k not in CONFIG_INVARIANT_KEYS}
    for tag in tags[1:]:
        other = {k: v for k, v in configs[tag].items() if k not in CONFIG_INVARIANT_KEYS}
        if other != base:
            base_keys, other_keys = set(configs[base_tag]), set(configs[tag])
            diffs = []
            for key in sorted((base_keys | other_keys) - set(CONFIG_INVARIANT_KEYS)):
                if configs[base_tag].get(key) != configs[tag].get(key):
                    diffs.append(key)
            raise MergeError(
                f"{cell}_{policy}: configs of {base_tag!r} and {tag!r} differ in "
                f"field(s) other than {CONFIG_INVARIANT_KEYS}: {diffs}"
            )


def check_seeds_disjoint(cell: str, policy: str, configs: dict[str, dict]) -> list[int]:
    seen: dict[int, str] = {}
    for tag, cfg in configs.items():
        for seed in cfg["task_seeds"]:
            if seed in seen:
                raise MergeError(
                    f"{cell}_{policy}: task seed {seed} appears in both "
                    f"{seen[seed]!r} and {tag!r} -- refusing to merge overlapping seeds"
                )
            seen[seed] = tag
    return sorted(seen)


def merge_file(
    name: str,
    sources: dict[str, Path],
    degrees: list[int],
    union_seeds: list[int],
) -> tuple[list[str], dict[str, int], list[str]]:
    """Concatenate one file across sources, ordered degree-major then seed.

    Also returns ``source_tags``, parallel to ``ordered_lines``, naming the
    ``--from-tags`` entry each line came from (each episode key comes from
    exactly one source, since sources' task seeds are disjoint).
    """
    degree_order = {d: i for i, d in enumerate(degrees)}
    seed_order = {s: i for i, s in enumerate(union_seeds)}
    groups: dict[str, list[tuple[str, str]]] = {}
    counts: dict[str, int] = {}
    for tag, rdir in sources.items():
        path = rdir / name
        if not path.exists():
            continue
        for line in path.read_text(encoding="utf-8").splitlines():
            if not line.strip():
                continue
            record = json.loads(line)
            key = episode_key(record)
            groups.setdefault(key, []).append((line, tag))
            counts[tag] = counts.get(tag, 0) + 1

    def sort_key(key: str) -> tuple[int, int, int]:
        degree, seed, repeat = parse_episode_key(key)
        return (degree_order.get(degree, degree), seed_order.get(seed, seed), repeat)

    ordered_lines: list[str] = []
    source_tags: list[str] = []
    for key in sorted(groups, key=sort_key):
        for line, tag in groups[key]:
            ordered_lines.append(line)
            source_tags.append(tag)
    return ordered_lines, counts, source_tags


def collect_failed_episodes(
    lines: list[str], source_tags: list[str]
) -> list[dict[str, Any]]:
    """Episode records with a non-``"ok"`` status, in merged (output) order."""
    failed = []
    for line, source_tag in zip(lines, source_tags):
        record = json.loads(line)
        status = record.get("status")
        if status == "ok" or status is None:
            continue
        key = episode_key(record)
        degree, task_seed, _repeat = parse_episode_key(key)
        error = record.get("error") or ""
        failed.append(
            {
                "episode_id": key,
                "d": degree,
                "task_seed": task_seed,
                "status": status,
                "error": error[:200],
                "source_tag": source_tag,
            }
        )
    return failed


def build_merged_config(
    out_tag: str, cell: str, policy: str, base_config: dict, union_seeds: list[int], from_tags: list[str]
) -> dict:
    merged = json.loads(json.dumps(base_config))  # deep copy via round-trip
    merged["name"] = f"{out_tag}_{cell}_{policy}"
    merged["output_root"] = f"runs/agents/{out_tag}"
    merged["task_seeds"] = list(union_seeds)
    merged["notes"] = (
        f"{merged.get('notes', '')} Merged by scripts/merge_runs.py from "
        f"{from_tags} (union of task_seeds)."
    ).strip()
    return merged


def sum_numeric_dicts(dicts: list[dict]) -> dict[str, float]:
    total: dict[str, float] = {}
    for d in dicts:
        for key, value in (d or {}).items():
            if isinstance(value, (int, float)):
                total[key] = total.get(key, 0) + value
    return total


def plan_cell(
    out_tag: str,
    from_tags: list[str],
    cell: str,
    policy: str,
    configs_root: Path,
    runs_root: Path,
    allow_failed: bool = False,
) -> dict:
    """Validate one cell and return everything needed to write it out."""
    configs: dict[str, dict] = {}
    rdirs: dict[str, Path] = {}
    summaries: dict[str, dict] = {}
    for tag in from_tags:
        cfg_path = config_path(configs_root, tag, cell, policy)
        if not cfg_path.exists():
            raise MergeError(f"{tag}/{cell}_{policy}: config not found: {cfg_path}")
        cfg = load_json(cfg_path)
        rdir = run_dir(runs_root, tag, cell, policy)
        configs[tag] = cfg
        rdirs[tag] = rdir
        summaries[tag] = check_source(tag, cell, policy, cfg, rdir, allow_failed=allow_failed)

    check_configs_compatible(cell, policy, configs)
    union_seeds = check_seeds_disjoint(cell, policy, configs)

    base_tag = from_tags[0]
    degrees = list(configs[base_tag]["degrees"])
    merged_config = build_merged_config(out_tag, cell, policy, configs[base_tag], union_seeds, from_tags)

    return {
        "cell": cell,
        "policy": policy,
        "configs": configs,
        "rdirs": rdirs,
        "summaries": summaries,
        "degrees": degrees,
        "union_seeds": union_seeds,
        "merged_config": merged_config,
    }


def write_cell(out_tag: str, plan: dict, runs_root: Path) -> None:
    cell, policy = plan["cell"], plan["policy"]
    run_id = f"{out_tag}_{cell}_{policy}"
    out_run_dir = run_dir(runs_root, out_tag, cell, policy)
    out_run_dir.mkdir(parents=True, exist_ok=True)

    records: dict[str, int] = {}
    failed_episodes: list[dict[str, Any]] = []
    for name in MERGED_FILES:
        lines, counts, source_tags = merge_file(
            name, plan["rdirs"], plan["degrees"], plan["union_seeds"]
        )
        if not lines:
            continue
        (out_run_dir / name).write_text("\n".join(lines) + "\n", encoding="utf-8")
        records[name] = len(lines)
        if name == "episodes.jsonl":
            failed_episodes = collect_failed_episodes(lines, source_tags)

    statuses: dict[str, int] = {}
    for line in (out_run_dir / "episodes.jsonl").read_text(encoding="utf-8").splitlines():
        if not line.strip():
            continue
        status = json.loads(line).get("status", "unknown")
        statuses[status] = statuses.get(status, 0) + 1

    llm_usage = sum_numeric_dicts([s.get("llm_usage", {}) for s in plan["summaries"].values()])
    per_shard_wall_seconds: dict[str, float] = {}
    for s in plan["summaries"].values():
        per_shard_wall_seconds.update(s.get("per_shard_wall_seconds") or {})
    total_shards = sum(int(s.get("shards") or 0) for s in plan["summaries"].values())
    total_wall_seconds = sum(float(s.get("wall_seconds") or 0) for s in plan["summaries"].values())

    manifest = {
        "run_id": run_id,
        "created_at": utc_now(),
        "config": plan["merged_config"],
        "merged_from": [
            {
                "tag": tag,
                "run_dir": str(plan["rdirs"][tag]),
                "task_seeds": list(plan["configs"][tag]["task_seeds"]),
            }
            for tag in plan["configs"]
        ],
        "failed_episodes": failed_episodes,
    }
    (out_run_dir / "manifest.json").write_text(
        json.dumps(manifest, indent=2, ensure_ascii=False) + "\n", encoding="utf-8"
    )

    run_summary = {
        "run_id": run_id,
        "finished_at": utc_now(),
        "wall_seconds": total_wall_seconds,
        "shards": total_shards,
        # Sources' own failed_shards are not copied (they name source-tag
        # shard ids, not this merged cell); a merge with --allow-failed
        # records the underlying failures as failed_episodes instead, and
        # statuses (below) is recomputed from the merged episodes.jsonl, so
        # it already reflects the true (non-"ok") counts.
        "failed_shards": [],
        "records": records,
        "statuses": statuses,
        "failed_episodes": failed_episodes,
        "llm_usage": llm_usage,
        "per_shard_wall_seconds": per_shard_wall_seconds,
    }
    (out_run_dir / "run_summary.json").write_text(
        json.dumps(run_summary, indent=2, ensure_ascii=False) + "\n", encoding="utf-8"
    )
    # No configs/agents/<out_tag>/ folder is written: an out-tag is a pooled
    # analysis view over its source tags' run data, not a new task seed --
    # the merged config lives only in this manifest.json (dc_table.py reads
    # it from there).


def merge_all(
    out_tag: str,
    from_tags: list[str],
    configs_root: Path | None = None,
    runs_root: Path | None = None,
    allow_failed: bool = False,
) -> list[dict]:
    if len(from_tags) < 2:
        raise MergeError("--from-tags needs at least 2 tags to merge")
    if len(set(from_tags)) != len(from_tags):
        raise MergeError(f"--from-tags has duplicate entries: {from_tags}")
    configs_root = configs_root or (REPO_ROOT / "configs" / "agents")
    runs_root = runs_root or (REPO_ROOT / "runs" / "agents")

    plans = []
    errors = []
    for cell in CELLS:
        for policy in POLICIES:
            try:
                plans.append(
                    plan_cell(
                        out_tag, from_tags, cell, policy, configs_root, runs_root,
                        allow_failed=allow_failed,
                    )
                )
            except MergeError as error:
                errors.append(str(error))
    if errors:
        raise MergeError("refusing to merge:\n" + "\n".join(f"  - {e}" for e in errors))

    for plan in plans:
        write_cell(out_tag, plan, runs_root)
    return plans


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out-tag", required=True)
    parser.add_argument("--from-tags", nargs="+", required=True)
    parser.add_argument("--configs-dir", type=Path, default=None, help="override configs/agents/ root")
    parser.add_argument("--runs-dir", type=Path, default=None, help="override runs/agents/ root")
    parser.add_argument(
        "--allow-failed", action="store_true",
        help=(
            "merge a source cell anyway when its only problem is episodes with a "
            "terminal failure status (e.g. policy_failed) -- those episode records "
            "are included as-is and listed in the merged cell's manifest.json / "
            "run_summary.json failed_episodes. Still refuses on missing files, "
            "missing episodes, config mismatch, or overlapping seeds. Default off."
        ),
    )
    args = parser.parse_args(argv)

    try:
        plans = merge_all(
            args.out_tag, args.from_tags, args.configs_dir, args.runs_dir,
            allow_failed=args.allow_failed,
        )
    except MergeError as error:
        print(f"error: {error}", file=sys.stderr)
        return 1

    for plan in plans:
        print(
            f"merged {plan['cell']}_{plan['policy']}: "
            f"task_seeds={plan['union_seeds']} from {list(plan['configs'])}"
        )
    print(f"\nout_tag={args.out_tag}: {len(plans)} cells merged from {args.from_tags}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
