"""Task instances and the public/hidden split of an environment."""

from __future__ import annotations

from abc import ABC, abstractmethod
from dataclasses import dataclass
from typing import Sequence

import numpy as np

from ...scaling_model import make_initial_pairs, make_truth
from ..hypotheses import Encoding
from ..schemas import (
    ComponentSpec,
    EvidenceRecord,
    ExperimentCondition,
    ExperimentResult,
    Pair,
    PrivateObservation,
)


@dataclass(frozen=True)
class TaskInstance:
    """Hidden mechanism plus Mode-B initialisation, shared by all environments.

    Generated by the reference routines so a paired task is identical across
    degrees, policies and environment kinds.
    """

    seed: int
    encoding: Encoding
    truth_values: tuple[int, ...]
    truth_pairs: tuple[Pair, ...]
    primary_groups: tuple[int, ...]
    initial_pairs: tuple[tuple[Pair, ...], ...]

    def is_positive(self, pair: Pair) -> bool:
        family, variant = pair
        return self.truth_values[family] == variant

    @property
    def truth_set(self) -> frozenset[Pair]:
        return frozenset(self.truth_pairs)

    def initial_incorrect(self) -> int:
        truth = self.truth_set
        return sum(pair not in truth for group in self.initial_pairs for pair in group)


def build_task_instance(
    *, agents: int, encoding: Encoding, task_size: int, seed: int, initial_width: int
) -> TaskInstance:
    encoding.check()
    truth_values, _key, _used, truth_pairs, primary_groups = make_truth(
        agents, encoding.families, task_size, encoding.variants, seed, encoding.bits
    )
    initial = make_initial_pairs(
        agents,
        list(truth_pairs),
        list(primary_groups),
        encoding.pair_count,
        seed,
        initial_width,
    )
    return TaskInstance(
        seed=seed,
        encoding=encoding,
        truth_values=tuple(truth_values),
        truth_pairs=tuple(encoding.pair(index) for index in truth_pairs),
        primary_groups=tuple(primary_groups),
        initial_pairs=tuple(
            tuple(encoding.pair(index) for index in group) for group in initial
        ),
    )


class Environment(ABC):
    """Runs experiments against a hidden mechanism.

    ``execute`` is the only budgeted operation.  Prediction helpers are public
    because an agent may simulate its own hypotheses at its own compute cost;
    hold-out evaluation is reserved for :mod:`src.agent_system.evaluation`.
    """

    kind: str = "abstract"
    notes: str = ""

    def __init__(self, task: TaskInstance) -> None:
        self.task = task
        self.experiments_executed = 0
        self.failures: dict[str, int] = {}

    # -- public surface --------------------------------------------------
    @abstractmethod
    def component_library(self) -> tuple[ComponentSpec, ...]:
        ...

    def experiment_library(self) -> tuple[ExperimentCondition, ...]:
        return ()

    def initial_observations(self, agent_index: int) -> tuple[PrivateObservation, ...]:
        return ()

    def requires_experiment_id(self) -> bool:
        return bool(self.experiment_library())

    def select_experiment(
        self,
        *,
        pair: Pair,
        parent_components: tuple[Pair, ...],
        frontier_components: tuple[tuple[Pair, ...], ...],
        seed: int,
        round_number: int,
        agent_index: int,
        slot: int,
    ) -> str | None:
        """A protocol-level override of the policy's ``experiment_id``.

        ``None`` -- the default, and what every environment does unless a knob
        says otherwise -- keeps whatever the policy chose.  It exists for the
        selection rules the paper states as part of the *protocol* rather than
        as part of the agent's reasoning, such as tcas ``max_containment``.
        """
        return None

    def new_evidence_store(self, encoding: Encoding):
        """The store the runner keeps per agent.

        Component-level environments share one implementation; an environment
        whose experiment is a complete assignment, and whose pruning is
        therefore by subset, returns its own.
        """
        from ..evidence import EvidenceStore

        return EvidenceStore(encoding)

    # -- budgeted operation ----------------------------------------------
    async def execute(
        self,
        *,
        pair: Pair,
        experiment_id: str | None,
        owner: int,
        round_number: int,
        event_id: str,
        parent_components: tuple[Pair, ...] = (),
    ) -> ExperimentResult:
        """Run one experiment.

        ``parent_components`` is the hypothesis the tested component refines.
        Component-level environments ignore it; it is needed only where the
        experiment is a complete assignment that has to contain the whole
        proposed hypothesis.
        """
        self.experiments_executed += 1
        record = EvidenceRecord(
            event_id=event_id,
            pair=pair,
            outcome="positive" if self.task.is_positive(pair) else "negative",
            origin_agent=owner,
            created_round=round_number,
            experiment_id=experiment_id,
        )
        observation = self.observe(experiment_id, owner=owner, event_id=event_id)
        return ExperimentResult(evidence=record, observation=observation)

    def observe(
        self, experiment_id: str | None, *, owner: int, event_id: str
    ) -> PrivateObservation | None:
        return None

    # -- prediction (unbudgeted compute) ---------------------------------
    def supports_prediction(self) -> bool:
        return False

    def predict(
        self, components: Sequence[Pair], condition: ExperimentCondition
    ) -> np.ndarray | None:
        return None

    # -- hidden, evaluator-only -------------------------------------------
    def scores_heldout(self) -> bool:
        """Whether ``heldout_error`` is defined for this environment.

        Separate from :meth:`supports_prediction`, which is about an agent
        being able to simulate its own hypotheses: tcas has a hold-out but
        nothing to simulate, and a GRN hypothesis can be stated but not scored.
        """
        return self.supports_prediction()

    def heldout_conditions(self) -> tuple[ExperimentCondition, ...]:
        return ()

    def heldout_error(self, components: Sequence[Pair]) -> float:
        return float("nan")

    def diagnostics(self) -> dict[str, object]:
        return {"experiments_executed": self.experiments_executed, "failures": dict(self.failures)}
